name: railway-delay-archiver
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - requests
      - tqdm
      - protobuf
      - gtfs-realtime-bindings
      - pandas
      - numpy
      - python-dateutil
      - geopy
      - shapely
      - meteostat
      - python-dotenv
      - loguru
      - pyyaml
      - matplotlib
      - seaborn
      - jupyterlab
      - ipywidgets
      - nbconvert
      - black
